spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: itaca
    password: itaca

dbinstall:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: itaca
    password: itaca

